import { loader } from "fumadocs-core/source";
// Generated by fumadocs-mdx from source.config.ts on every dev start and build.
import { docs } from "../../.source/server";

export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
